server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080
spring:
  datasource:
    password: registration
    url: jdbc:postgresql://localhost:5432/registration
    username: registration
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true
